#!/usr/bin/env bash
set -euo pipefail

echo "=== Enable Firebase Authentication Providers ==="
echo ""
echo "The following steps must be completed manually in the Firebase Console"
echo "and Google Cloud Console. This script provides a step-by-step guide."
echo ""
echo "Project: nexion-ai-prod"
echo ""
echo "-------------------------------------------------------"
echo "Step 1: Enable Google Sign-In"
echo "-------------------------------------------------------"
echo "  1. Go to Firebase Console > Authentication > Sign-in method"
echo "     https://console.firebase.google.com/project/nexion-ai-prod/authentication/providers"
echo "  2. Click 'Google' in the provider list"
echo "  3. Toggle 'Enable' to ON"
echo "  4. Set a public-facing project name and support email"
echo "  5. Click 'Save'"
echo ""
echo "-------------------------------------------------------"
echo "Step 2: Enable Apple Sign-In"
echo "-------------------------------------------------------"
echo "  1. Go to Firebase Console > Authentication > Sign-in method"
echo "     https://console.firebase.google.com/project/nexion-ai-prod/authentication/providers"
echo "  2. Click 'Apple' in the provider list"
echo "  3. Toggle 'Enable' to ON"
echo "  4. Click 'Save'"
echo "  NOTE: You need a paid Apple Developer account for Apple Sign-In."
echo ""
echo "-------------------------------------------------------"
echo "Step 3: Configure OAuth Consent Screen"
echo "-------------------------------------------------------"
echo "  1. Go to GCP Console > APIs & Services > OAuth consent screen"
echo "     https://console.cloud.google.com/apis/credentials/consent?project=nexion-ai-prod"
echo "  2. Set the app name, user support email, and developer contact email"
echo "  3. Add any required scopes (email, profile, openid)"
echo "  4. Save and submit for verification if publishing externally"
echo ""
echo "-------------------------------------------------------"
echo "Step 4: Add SHA-1 Fingerprint for Android"
echo "-------------------------------------------------------"
echo "  1. Get your debug SHA-1 fingerprint:"
echo "     cd android && ./gradlew signingReport"
echo "  2. Go to Firebase Console > Project Settings > Your apps > Android app"
echo "     https://console.firebase.google.com/project/nexion-ai-prod/settings/general"
echo "  3. Click 'Add fingerprint' and paste the SHA-1 value"
echo "  4. Download the updated google-services.json and place it in android/app/"
echo ""
echo "-------------------------------------------------------"
echo "Step 5: Configure Apple Services ID for Sign in with Apple"
echo "-------------------------------------------------------"
echo "  1. Go to Apple Developer portal > Certificates, Identifiers & Profiles"
echo "     https://developer.apple.com/account/resources/identifiers/list/serviceId"
echo "  2. Create a new Services ID if one does not exist"
echo "  3. Enable 'Sign in with Apple' and configure the domain and return URL"
echo "  4. The return URL should be:"
echo "     https://nexion-ai-prod.firebaseapp.com/__/auth/handler"
echo "  5. Copy the Services ID and paste it in the Firebase Console under"
echo "     Authentication > Sign-in method > Apple > Services ID"
echo ""
echo "-------------------------------------------------------"
echo "Useful Links"
echo "-------------------------------------------------------"
echo "  Firebase Console:  https://console.firebase.google.com/project/nexion-ai-prod"
echo "  GCP Console:       https://console.cloud.google.com/home/dashboard?project=nexion-ai-prod"
echo "  Apple Developer:   https://developer.apple.com/account"
echo ""
echo "=== End of guide ==="
