// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAonvVAISq0qs_aYSTzU5qtTPR-exW0o6g',
    appId: '1:627959972375:web:682cd186b36da68074d252',
    messagingSenderId: '627959972375',
    projectId: 'nexion-ai-prod',
    authDomain: 'nexion-ai-prod.firebaseapp.com',
    storageBucket: 'nexion-ai-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIu_32bk8aziHOj9SmQVSqj5QvfL5yI3A',
    appId: '1:627959972375:android:8346ba3689eda0d574d252',
    messagingSenderId: '627959972375',
    projectId: 'nexion-ai-prod',
    storageBucket: 'nexion-ai-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHrwWoajCjHNRHtu9N0TAZR8k8WT5P0vM',
    appId: '1:627959972375:ios:64cd413e441428a374d252',
    messagingSenderId: '627959972375',
    projectId: 'nexion-ai-prod',
    storageBucket: 'nexion-ai-prod.firebasestorage.app',
    iosBundleId: 'com.skynergroup.coupleSync',
  );
}
