// File generated by FlutterFire CLI.
// This is a placeholder file. Run `flutterfire configure` to generate
// the actual configuration for your Firebase project.
//
// MANUAL SETUP REQUIRED:
// 1. Install FlutterFire CLI: dart pub global activate flutterfire_cli
// 2. Run: flutterfire configure --project=nexion-ai-prod
// 3. This will generate the proper configuration for iOS, Android, and Web
//
// The FlutterFire CLI will replace this file with platform-specific
// Firebase configuration options.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Placeholder implementation - requires manual configuration via FlutterFire CLI.
/// Run `flutterfire configure --project=nexion-ai-prod` to generate proper options.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Placeholder web configuration.
  /// TODO: Replace with actual values from `flutterfire configure`
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'nexion-ai-prod',
    authDomain: 'nexion-ai-prod.firebaseapp.com',
    storageBucket: 'nexion-ai-prod.appspot.com',
  );

  /// Placeholder Android configuration.
  /// TODO: Replace with actual values from `flutterfire configure`
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'nexion-ai-prod',
    storageBucket: 'nexion-ai-prod.appspot.com',
  );

  /// Placeholder iOS configuration.
  /// TODO: Replace with actual values from `flutterfire configure`
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'nexion-ai-prod',
    storageBucket: 'nexion-ai-prod.appspot.com',
    iosBundleId: 'com.skyner.coupleSync',
  );

  /// Placeholder macOS configuration.
  /// TODO: Replace with actual values from `flutterfire configure`
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'nexion-ai-prod',
    storageBucket: 'nexion-ai-prod.appspot.com',
    iosBundleId: 'com.skyner.coupleSync',
  );

  /// Placeholder Windows configuration.
  /// TODO: Replace with actual values from `flutterfire configure`
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'nexion-ai-prod',
    storageBucket: 'nexion-ai-prod.appspot.com',
  );

  /// Placeholder Linux configuration.
  /// TODO: Replace with actual values from `flutterfire configure`
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'YOUR_LINUX_API_KEY',
    appId: 'YOUR_LINUX_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'nexion-ai-prod',
    storageBucket: 'nexion-ai-prod.appspot.com',
  );
}
