// Mocks generated by Mockito 5.4.6 from annotations
// in couple_sync/test/services/providers/calendar_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:couple_sync/core/models/time_block.dart' as _i5;
import 'package:couple_sync/services/calendar_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CalendarService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarService extends _i1.Mock implements _i2.CalendarService {
  MockCalendarService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<bool> get connectionStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#connectionStateChanges),
            returnValue: _i3.Stream<bool>.empty(),
          )
          as _i3.Stream<bool>);

  @override
  _i3.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<List<({DateTime end, DateTime start})>> fetchFreebusy() =>
      (super.noSuchMethod(
            Invocation.method(#fetchFreebusy, []),
            returnValue:
                _i3.Future<List<({DateTime end, DateTime start})>>.value(
                  <({DateTime end, DateTime start})>[],
                ),
          )
          as _i3.Future<List<({DateTime end, DateTime start})>>);

  @override
  List<_i5.TimeBlock> convertToTimeBlocks(
    List<({DateTime end, DateTime start})>? busyIntervals, {
    required String? userId,
    required String? timezone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #convertToTimeBlocks,
              [busyIntervals],
              {#userId: userId, #timezone: timezone},
            ),
            returnValue: <_i5.TimeBlock>[],
          )
          as List<_i5.TimeBlock>);

  @override
  _i3.Future<DateTime?> getLastSyncTime() =>
      (super.noSuchMethod(
            Invocation.method(#getLastSyncTime, []),
            returnValue: _i3.Future<DateTime?>.value(),
          )
          as _i3.Future<DateTime?>);

  @override
  _i3.Future<void> updateLastSyncTime() =>
      (super.noSuchMethod(
            Invocation.method(#updateLastSyncTime, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> shouldAutoSync() =>
      (super.noSuchMethod(
            Invocation.method(#shouldAutoSync, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
