// Mocks generated by Mockito 5.4.6 from annotations
// in couple_sync/test/services/providers/firestore_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:couple_sync/core/models/models.dart' as _i4;
import 'package:couple_sync/services/firestore_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i2.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.UserModel?> getUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [uid]),
            returnValue: _i3.Future<_i4.UserModel?>.value(),
          )
          as _i3.Future<_i4.UserModel?>);

  @override
  _i3.Future<void> createUser(String? uid, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [uid, data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateUser(String? uid, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [uid, data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.CoupleModel?> getCouple(String? coupleId) =>
      (super.noSuchMethod(
            Invocation.method(#getCouple, [coupleId]),
            returnValue: _i3.Future<_i4.CoupleModel?>.value(),
          )
          as _i3.Future<_i4.CoupleModel?>);

  @override
  _i3.Future<String> createCouple(_i4.CoupleModel? couple) =>
      (super.noSuchMethod(
            Invocation.method(#createCouple, [couple]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#createCouple, [couple]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> createInvite(String? code, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createInvite, [code, data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.InviteModel?> getInvite(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getInvite, [code]),
            returnValue: _i3.Future<_i4.InviteModel?>.value(),
          )
          as _i3.Future<_i4.InviteModel?>);

  @override
  _i3.Future<void> updateInvite(String? code, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateInvite, [code, data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.TimeBlock>> getBlocks(String? coupleId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getBlocks, [coupleId, userId]),
            returnValue: _i3.Future<List<_i4.TimeBlock>>.value(
              <_i4.TimeBlock>[],
            ),
          )
          as _i3.Future<List<_i4.TimeBlock>>);

  @override
  _i3.Future<String> createBlock(String? coupleId, _i4.TimeBlock? block) =>
      (super.noSuchMethod(
            Invocation.method(#createBlock, [coupleId, block]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#createBlock, [coupleId, block]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> updateBlock(
    String? coupleId,
    String? blockId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBlock, [coupleId, blockId, data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteBlock(String? coupleId, String? blockId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBlock, [coupleId, blockId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.OverlapResult?> getOverlap(String? coupleId) =>
      (super.noSuchMethod(
            Invocation.method(#getOverlap, [coupleId]),
            returnValue: _i3.Future<_i4.OverlapResult?>.value(),
          )
          as _i3.Future<_i4.OverlapResult?>);
}
